name: My First Github Workflow Action
on: [push]
jobs:
  build_and_deploy_the_application:
    runs-on: ubuntu-latest
    outputs:
      sharedData: ${{ steps.firstJob.outputs.sharedData }}
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:
      - name: Cloning the Repo into the Virtual Container
        uses: actions/checkout@v2
      - name: Installing the Node version 16 in the Container
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Installing the node_modules in the Virtual Container
        run: yarn
      - name: Creating the Build of the project
        run: yarn build
      - name: Setting the Vercel environment in the Container
        run: |
          cd build
          mkdir .vercel
          cd .vercel
          touch project.json
          echo '{\"orgId\":\"$VERCEL_ORG_ID\",\"projectId\":\"$VERCEL_PROJECT_ID\"}' > project.json
      - name: Deploying the project to the Vercel site
        run: yarn deploy
      - name: Specify the data that is to be shared with other jobs
        id: firstJob
        run: echo "::set-output name=sharedData::data-from-first-job-is-this"
      - name: Confirmation that the Build is completed and Deployed to the Vercel
        run: echo "Successfully build the project and deployed it to the Vercel!"
  test-job:
    needs: build_and_deploy_the_application
    runs-on: ubuntu-18.04
    env:
      SHARED_JOB_DATA: ${{ needs.build_and_deploy_the_application.outputs.sharedData }}
    steps:
      - name: Testing the application
        run: echo $SHARED_JOB_DATA
