name: My First Github Workflow Action
on: [push]
jobs:
  build-the-application:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning the Repo into the Virtual Container
        uses: actions/checkout@v2
      - name: Installing the Node version 16 in the Container
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Installing the node_modules in the Virtual Container
        run: yarn
      - name: Creating the Build of the project
        run: yarn build
      - name: Setting the Vercel environment in the Container
        run: |
          cd build
          mkdir .vercel
          cd .vercel
          touch project.json
          echo '{"orgId":"rJZUctatKQzgB6NH7ZVZzMnx","projectId":"prj_KZ55aCau4WNtjn8W4TuQjGHlqePT"}' > project.json
      - name: Deploying the project to the Vercel site
        run: yarn deploy
      - name: Confirmation that the Build is completed and Deployed to the Vercel
        run: echo "Successfully build the project and deployed it to the Vercel!"
