name: My First Github Workflow Action
on: [push]
jobs:
  build-the-application:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning the Repo into the Virtual Container
        uses: actions/checkout@v2
      - name: Installing the Node version 16 in the Container
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Installing the node_modules in the Virtual Container
        run: yarn
      - name: Creating the Build of the project
        run: yarn build
      - name: Confirmation that the build is completed
        run: echo "Build commpleted successfully!"
